import { jsPDF } from "jspdf";

interface ExportItem {
  title: string;
  items: { name: string; description: string; code?: string }[];
}

export const usePdfExport = () => {
  const exportToPdf = (data: ExportItem[], filename: string, title: string) => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const margin = 20;
    let yPosition = margin;

    // Title
    doc.setFontSize(24);
    doc.setTextColor(0, 255, 136);
    doc.text(title, pageWidth / 2, yPosition, { align: "center" });
    yPosition += 15;

    // Subtitle
    doc.setFontSize(10);
    doc.setTextColor(150, 150, 150);
    doc.text("Generated by Qusay Security Platform", pageWidth / 2, yPosition, { align: "center" });
    yPosition += 20;

    data.forEach((section) => {
      // Check if we need a new page
      if (yPosition > pageHeight - 40) {
        doc.addPage();
        yPosition = margin;
      }

      // Section title
      doc.setFontSize(16);
      doc.setTextColor(0, 200, 100);
      doc.text(section.title, margin, yPosition);
      yPosition += 10;

      // Draw line
      doc.setDrawColor(0, 255, 136);
      doc.line(margin, yPosition, pageWidth - margin, yPosition);
      yPosition += 8;

      section.items.forEach((item, index) => {
        // Check if we need a new page
        if (yPosition > pageHeight - 30) {
          doc.addPage();
          yPosition = margin;
        }

        // Item number and name
        doc.setFontSize(11);
        doc.setTextColor(255, 255, 255);
        doc.text(`${index + 1}. ${item.name}`, margin + 5, yPosition);
        yPosition += 6;

        // Description
        doc.setFontSize(9);
        doc.setTextColor(180, 180, 180);
        const descLines = doc.splitTextToSize(item.description, pageWidth - margin * 2 - 10);
        doc.text(descLines, margin + 10, yPosition);
        yPosition += descLines.length * 5 + 3;

        // Code if exists
        if (item.code) {
          if (yPosition > pageHeight - 50) {
            doc.addPage();
            yPosition = margin;
          }
          
          doc.setFontSize(8);
          doc.setTextColor(0, 255, 136);
          const codeLines = doc.splitTextToSize(item.code, pageWidth - margin * 2 - 15);
          const maxLines = Math.min(codeLines.length, 15);
          doc.text(codeLines.slice(0, maxLines), margin + 10, yPosition);
          yPosition += maxLines * 4 + 5;
          
          if (codeLines.length > 15) {
            doc.setTextColor(150, 150, 150);
            doc.text("... (code truncated)", margin + 10, yPosition);
            yPosition += 5;
          }
        }

        yPosition += 3;
      });

      yPosition += 10;
    });

    // Footer on each page
    const totalPages = doc.internal.pages.length - 1;
    for (let i = 1; i <= totalPages; i++) {
      doc.setPage(i);
      doc.setFontSize(8);
      doc.setTextColor(100, 100, 100);
      doc.text(`Page ${i} of ${totalPages}`, pageWidth / 2, pageHeight - 10, { align: "center" });
      doc.text("@0oscp", pageWidth - margin, pageHeight - 10, { align: "right" });
    }

    doc.save(filename);
  };

  return { exportToPdf };
};
